--insert into Authorities (creationDate, version, authority, username, id) values (null, 0, 'ROLE_USER', 'TEST1234', -1)
insert into User (dtype, role, version, email, enabled, username, lastName, password, phone, id) values ('User', 'ROLE_USER', 0, null, 1, 'TEST1234', 'Test User', '1234', null, -1)
INSERT INTO SECURITYQUESTION VALUES(1, 0,'What''s the name of your first pet?')
INSERT INTO SECURITYQUESTION VALUES(2, 0,'What''s your mother maiden name?')
INSERT INTO SECURITYQUESTION VALUES(3, 0,'Which city did you get your first job?')
INSERT INTO SECURITYQUESTION VALUES(4, 0,'Which city was your father born?')
INSERT INTO SECURITYQUESTION VALUES(5, 0,'Which city were you born?')
INSERT INTO SECURITYQUESTION VALUES(6, 0,'What''s the name of your first teacher?')